config/routes.rb
Rails.application.routes.draw do
  # created when installed devise and the views for the users
  devise_for :users
  # get 'pages/home'

  # making the home pages to be the root 
  # when we use #, that means it's an action
  # so we are interested in the home action by doing #home
  root 'pages#home'

  #settings up ROUTE for the about page
  get 'about' => 'pages#about'

  # setting up the ROUTE for the contactus page by linking the action to the home page using the hash rocket symbol =>
  get 'contactus' => 'pages#contactus'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  # Creating an about action
  def about
  end

  #Creating the Contact us section
  def contactus
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
      </a>
      <%=link_to root_path, class: 'navbar-brand' do %>
        <i class="fa fa-check-square fa-1x" style="color:rgb(6,170,6)"></i> <span style="color:red;"> n</span>Tasks
      <%end%>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!-- checking if a user has signed up successfully -->
        <%if current_user %>
          <!-- if yes then we will show them their account settings page -->
          <li> <%=link_to "Account Settings",edit_user_registration_path%> </li>
          <!-- Displaying the logout nav bar -->
          <li><%=link_to 'Log Out',destroy_user_session_path, method: :delete%> </li>
          <!-- Else we show the user the login and signup link -->
        <% else %>
          <!-- <li><a href="">Link</a></li> -->
          <li><%=link_to 'About',about_path %></li>
          <!-- Creating the login path -->
          <li><%=link_to 'Log In',new_user_session_path%></li>
          <li><%=link_to 'Contact',contactus_path %></li>
        <%end %>
        <li class="dropdown">
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>nTasks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/app/assets/stylesheets/device.css.scss">
  </head>
  <body class="bg">
    <!-- Rendering the navbar -->
    <%= render 'layouts/navbar' %>
    <div class="container" style="border-radius:25px";>
      <div class="text-center">
      <%= yield %>
      </div>
      
    </body>
  </div>
</html>

app/views/pages/about.html.erb
<div class="text-center">
<h3>About US</h3>
<h6>Manage your life today!</h6>
</div>

app/views/pages/contactus.html.erb
<h3>Welcome to the Contact page</h3>

app/views/pages/home.html.erb
<div id="home" class="jumbotron text-center">
  <h1 class="text-center"><i class="fa fa-check-square" style="color:rgb(6, 170, 6)"></i><span style="color:red;"> n</span>Tasks</h1>
  <p class="text-center">The Best Task Management system for those with goals!</p>
  <!-- centering the btn -->
  <%=link_to 'Sign Up',new_user_registration_path,class: "btn btn-primary btn-lg"%>
</div>